/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.model.Operater;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Profesor
 */
public class Prozor extends javax.swing.JFrame {

    private JPanel pnlPocetna;
    private JPanel pnlNbaTeams;
    private JPanel pnlPlayers;
    private JPanel pnlPlayerStats;
    private JPanel pnlGame;
    private JPanel pnlOperators;

    private Operater operater;

    /**
     * Creates new form Prozor
     */
    public Prozor(Operater operater) {
        initComponents();
        this.operater = operater;
        setTitle("NBA STATS APP " + operater.getIme() + " " + operater.getPrezime());
        pnlPocetna = new IzbornikPanel();
        pnlNbaTeams = new NbaTeamsPanel();
        pnlPlayers = new PlayerPanel();
        pnlPlayerStats = new PlayerStatPanel();
        pnlGame = new GamePanel();
        pnlOperators = new OperateriPanel();

        postaviPanel(pnlPocetna);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIzbornik = new javax.swing.JPanel();
        btnPocetna = new javax.swing.JButton();
        btnNbaTeams = new javax.swing.JButton();
        btnPlayerStats = new javax.swing.JButton();
        btnPlayers = new javax.swing.JButton();
        btnGames = new javax.swing.JButton();
        btnOperators = new javax.swing.JButton();
        pnlSadrzaj = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPocetna.setText("Izbornik");
        btnPocetna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPocetnaActionPerformed(evt);
            }
        });

        btnNbaTeams.setText("Nba teams");
        btnNbaTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNbaTeamsActionPerformed(evt);
            }
        });

        btnPlayerStats.setText("Player stats");
        btnPlayerStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerStatsActionPerformed(evt);
            }
        });

        btnPlayers.setText("Players");
        btnPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayersActionPerformed(evt);
            }
        });

        btnGames.setText("Games");
        btnGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGamesActionPerformed(evt);
            }
        });

        btnOperators.setText("Operators");
        btnOperators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperatorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIzbornikLayout = new javax.swing.GroupLayout(pnlIzbornik);
        pnlIzbornik.setLayout(pnlIzbornikLayout);
        pnlIzbornikLayout.setHorizontalGroup(
            pnlIzbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzbornikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIzbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOperators, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btnPocetna, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btnGames, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btnPlayerStats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btnPlayers, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btnNbaTeams, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlIzbornikLayout.setVerticalGroup(
            pnlIzbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzbornikLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnPocetna, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNbaTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnPlayerStats, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnGames, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnOperators, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pnlSadrzajLayout = new javax.swing.GroupLayout(pnlSadrzaj);
        pnlSadrzaj.setLayout(pnlSadrzajLayout);
        pnlSadrzajLayout.setHorizontalGroup(
            pnlSadrzajLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        pnlSadrzajLayout.setVerticalGroup(
            pnlSadrzajLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlIzbornik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSadrzaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIzbornik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSadrzaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPocetnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPocetnaActionPerformed
        postaviPanel(pnlPocetna);
    }//GEN-LAST:event_btnPocetnaActionPerformed

    private void btnNbaTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNbaTeamsActionPerformed
        postaviPanel(pnlNbaTeams);
    }//GEN-LAST:event_btnNbaTeamsActionPerformed

    private void btnPlayerStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerStatsActionPerformed
        postaviPanel(pnlPlayerStats);
    }//GEN-LAST:event_btnPlayerStatsActionPerformed

    private void btnPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayersActionPerformed
        postaviPanel(pnlPlayers);
    }//GEN-LAST:event_btnPlayersActionPerformed

    private void btnGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGamesActionPerformed
        postaviPanel(pnlGame);
    }//GEN-LAST:event_btnGamesActionPerformed

    private void btnOperatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperatorsActionPerformed
        postaviPanel(pnlOperators);
    }//GEN-LAST:event_btnOperatorsActionPerformed

    private void postaviPanel(JPanel panel) {
        pnlSadrzaj.removeAll();
        pnlSadrzaj.add(panel);
        panel.setSize(pnlSadrzaj.getSize());
        pnlSadrzaj.revalidate();
        pnlSadrzaj.repaint();

        resetPozadinaButton();

        switch (panel.getName()) {
            case "Menu":
                btnPocetna.setBackground(Color.GREEN);
                break;
            case "Nba teams":
                btnNbaTeams.setBackground(Color.GREEN);
                break;
            case "Players":
                btnPlayers.setBackground(Color.GREEN);
                break;
            case "Player stats":
                btnPlayerStats.setBackground(Color.GREEN);
                break;
            case "Games":
                btnGames.setBackground(Color.GREEN);
                break;
            case "Operators":
                btnOperators.setBackground(Color.GREEN);
                break;

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGames;
    private javax.swing.JButton btnNbaTeams;
    private javax.swing.JButton btnOperators;
    private javax.swing.JButton btnPlayerStats;
    private javax.swing.JButton btnPlayers;
    private javax.swing.JButton btnPocetna;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlIzbornik;
    private javax.swing.JPanel pnlSadrzaj;
    // End of variables declaration//GEN-END:variables

    private void resetPozadinaButton() {
        for (Component c : pnlIzbornik.getComponents()) {
            c.setBackground(Color.gray);
        }
    }
}
